### Dataset: PIB (Produit Intérieur Brut)

In [22]:
import pandas as pd
pib_df = pd.read_excel('/content/datasets2/PIB1.xlsx')
display(pib_df.head())

,PIB et valeurs ajoutées par secteurs d'activité (2015) \n\nAux prix de l'année 2015 en million de dinars\n\n\n,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,NaN,I trimestre 2010,II trimestre 2010,III trimestre 2010,IV trimestre 2010,I trimestre 2011,II trimestre 2011,III trimestre 2011,IV trimestre 2011,I trimestre 2012,...,III trimestre 2023,IV trimestre 2023,I trimestre 2024,II trimestre 2024,III trimestre 2024,IV trimestre 2024,I trimestre 2025,II trimestre 2025,III trimestre 2025,IV trimestre 2025
1,"Valeur ajoutée du secteur de l'agriculture, sy...",1498.5,1525.7,1554.3,1590.2,1659.6,1696.8,1736.4,1777.9,1808.4,...,1847.8,1890.1,2036.2,2052.4,2060.4,2128.7,2184.6,2254.3,2304.7,2390.8
2,Valeur ajoutée du secteur de l'extraction du p...,1285,1269.4,1287.7,1071.3,1021,1133.4,1144.2,989.7,1012.2,...,530.6,514.4,414.3,428.2,425.8,426.9,384.4,385.1,370.2,370
3,Valeur ajoutée du secteur de l'extraction des ...,212.1,209,217.5,236.1,92.6,89,104.4,106.5,119.5,...,136.5,142.5,147.2,148.1,157.1,183.7,172.6,203.6,206.9,207.2
4,Valeur ajoutée du secteur de l'industries agro...,653.8,643.4,682.4,641.5,638,662.7,678.8,687.3,690.5,...,791.3,800.8,836.1,817.2,828.9,810.3,910.6,820.7,850.4,859.5

In [23]:
# Select the row containing 'trimestre' information (index 1) and the 'PIB' row (index 30)
pib_df = pib_df_raw.iloc[[1, 30]]
display(pib_df)

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,64
1,NaN,I trimestre 2010,II trimestre 2010,III trimestre 2010,IV trimestre 2010,I trimestre 2011,II trimestre 2011,III trimestre 2011,IV trimestre 2011,I trimestre 2012,...,III trimestre 2023,IV trimestre 2023,I trimestre 2024,II trimestre 2024,III trimestre 2024,IV trimestre 2024,I trimestre 2025,II trimestre 2025,III trimestre 2025,IV trimestre 2025
30,Valeur ajoutée du secteur des produit Intérieu...,20611.2,20700.2,20876.3,20738,20045.9,20284.4,20353,20518.4,20769,...,23696.3,23768.4,23928.1,24004.8,24193.9,24355.2,24322.8,24772.8,24774.4,25017.3

In [24]:
# Extract the 'trimestre' row (index 1) and 'PIB' row (index 30) as Series, excluding the first descriptive column
dates_row = pib_df.iloc[0, 1:]
pib_row = pib_df.iloc[1, 1:]

# Create a new DataFrame with 'Date' and 'PIB' columns
df_transformed = pd.DataFrame({
    'Date': dates_row.values,
    'PIB': pib_row.values
})

# Convert 'PIB' column to numeric, coercing errors to NaN
df_transformed['PIB'] = pd.to_numeric(df_transformed['PIB'], errors='coerce')

display(df_transformed.head())

                 Date      PIB
0    I trimestre 2010  20611.2
1   II trimestre 2010  20700.2
2  III trimestre 2010  20876.3
3   IV trimestre 2010  20738.0
4    I trimestre 2011  20045.9

In [25]:
# Extract the year from the 'Date' column
df_transformed['Year'] = df_transformed['Date'].str.extract(r'(\d{4})').astype(int)

# Filter the DataFrame for the years 2015 to 2025
df_filtered = df_transformed[(df_transformed['Year'] >= 2015) & (df_transformed['Year'] <= 2025)].copy()

# Drop the temporary 'Year' column if not needed for further analysis
df_filtered = df_filtered.drop(columns=['Year'])

display(df_filtered.head())

                  Date      PIB
20    I trimestre 2015  22403.1
21   II trimestre 2015  22406.3
22  III trimestre 2015  22422.2
23   IV trimestre 2015  22570.5
24    I trimestre 2016  22555.4

In [26]:
display(df_filtered.tail())

                  Date      PIB
59   IV trimestre 2024  24355.2
60    I trimestre 2025  24322.8
61   II trimestre 2025  24772.8
62  III trimestre 2025  24774.4
63   IV trimestre 2025  25017.3

In [27]:
df_filtered

                  Date      PIB
20    I trimestre 2015  22403.1
21   II trimestre 2015  22406.3
22  III trimestre 2015  22422.2
23   IV trimestre 2015  22570.5
24    I trimestre 2016  22555.4
25   II trimestre 2016  22639.1
26  III trimestre 2016  22667.9
27   IV trimestre 2016  22943.2
28    I trimestre 2017  23082.7
29   II trimestre 2017  23067.2
30  III trimestre 2017  23206.7
31   IV trimestre 2017  23494.4
32    I trimestre 2018  23668.0
33   II trimestre 2018  23763.8
34  III trimestre 2018  23861.6
35   IV trimestre 2018  23978.2
36    I trimestre 2019  24108.3
37   II trimestre 2019  24199.1
38  III trimestre 2019  24225.4
39   IV trimestre 2019  24215.8
40    I trimestre 2020  23181.0
41   II trimestre 2020  19723.9
42  III trimestre 2020  22496.2
43   IV trimestre 2020  22664.0
44    I trimestre 2021  22922.1
45   II trimestre 2021  22894.2
46  III trimestre 2021  22982.9
47   IV trimestre 2021  23436.9
48    I trimestre 2022  23568.6
49   II trimestre 2022  23593.2
50  III trimestre 2022  23770.9
51   IV trimestre 2022  23842.1
52    I trimestre 2023  23804.0
53   II trimestre 2023  23680.2
54  III trimestre 2023  23696.3
55   IV trimestre 2023  23768.4
56    I trimestre 2024  23928.1
57   II trimestre 2024  24004.8
58  III trimestre 2024  24193.9
59   IV trimestre 2024  24355.2
60    I trimestre 2025  24322.8
61   II trimestre 2025  24772.8
62  III trimestre 2025  24774.4
63   IV trimestre 2025  25017.3

In [34]:
import pandas as pd

# Re-create df_filtered to ensure 'Date' column is present and in correct format
# This step is crucial because df_filtered might have been modified in a previous (failed) run
# Assuming df_transformed is still available from previous cells.
df_filtered = df_transformed[(df_transformed['Year'] >= 2015) & (df_transformed['Year'] <= 2025)].copy()
df_filtered = df_filtered.drop(columns=['Year']) # Ensure 'Year' column is dropped from df_filtered after filtering

# Mapping trimestre -> month start
quarter_map = {
    'I': '01',
    'II': '04',
    'III': '07',
    'IV': '10'
}

# Extract quarter and year from the 'Date' column
df_filtered['Quarter'] = df_filtered['Date'].str.split().str[0]
df_filtered['Year_str'] = df_filtered['Date'].str.extract(r'(\d{4})') # Using Year_str to avoid conflict with potential 'Year' col from df_transformed before filtering

# Convert to actual datetime (first day of the quarter)
df_filtered['Date'] = pd.to_datetime(df_filtered['Year_str'] + '-' + df_filtered['Quarter'].map(quarter_map) + '-01')

# Drop helper columns
df_filtered = df_filtered.drop(columns=['Quarter', 'Year_str'])

# Set Date as index
df_filtered.set_index('Date', inplace=True)

# Create daily index
# Ensure the index is a datetime index before finding min/max
daily_index = pd.date_range(start=df_filtered.index.min(), end=df_filtered.index.max(), freq='D')

# Reindex and interpolate
daily_df = df_filtered.reindex(daily_index).interpolate(method='cubic')
daily_df = daily_df.rename_axis('Date').reset_index()

display(daily_df.head(15))

         Date           PIB
0  2015-01-01  22403.100000
1  2015-01-02  22404.055484
2  2015-01-03  22404.979437
3  2015-01-04  22405.872230
4  2015-01-05  22406.734232
5  2015-01-06  22407.565813
6  2015-01-07  22408.367345
7  2015-01-08  22409.139196
8  2015-01-09  22409.881737
9  2015-01-10  22410.595338
10 2015-01-11  22411.280370
11 2015-01-12  22411.937203
12 2015-01-13  22412.566206
13 2015-01-14  22413.167750
14 2015-01-15  22413.742206

In [36]:
daily_df.to_excel('/content/datasets2/PIB_daily.xlsx', index=False)