### Dataset: Taux d'intérêt

In [16]:
import pandas as pd

taux_interet_df = pd.read_excel('/content/datasets2/taux_interet.xlsx')
display(taux_interet_df.head())

,Date/Indicateurs,Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre
0,2000-12-31,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875
1,2001-12-31,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875
2,2002-12-31,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875
3,2003-12-31,5.875,5.875,5.500,5.500,5.500,5.000,5.000,5.000,5.000,5.000,5.000,5.000
4,2004-12-31,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000

In [18]:
print(taux_interet_df.columns)

Index(['Date/Indicateurs ', 'Janvier', 'Février', 'Mars', 'Avril', 'Mai',
       'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre',
       'Décembre'],
      dtype='object')

In [21]:
# Supprimer les espaces invisibles autour des noms de colonnes
taux_interet_df.columns = taux_interet_df.columns.str.strip()

# Renommer pour plus de clarté
taux_interet_df.rename(columns={'Date/Indicateurs':'year'}, inplace=True)

# Vérifier
print(taux_interet_df.columns.tolist())
# ['year', 'Janvier', 'Février', ..., 'Décembre']

['year', 'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']

In [23]:
display(taux_interet_df)

,year,Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre
0,2000-12-31,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875
1,2001-12-31,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875
2,2002-12-31,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875,5.875
3,2003-12-31,5.875,5.875,5.500,5.500,5.500,5.000,5.000,5.000,5.000,5.000,5.000,5.000
4,2004-12-31,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000
5,2005-12-31,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000
6,2006-12-31,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.250,5.250,5.250,5.250
7,2007-12-31,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250
8,2008-12-31,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250,5.250
9,2009-12-31,5.250,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500
10,2010-12-31,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500,4.500
11,2011-12-31,4.500,4.500,4.500,4.500,4.500,4.000,4.000,4.000,3.500,3.500,3.500,3.500
12,2012-12-31,3.500,3.500,3.500,3.500,3.500,3.500,3.500,3.750,3.750,3.750,3.750,3.750
13,2013-12-31,3.750,3.750,4.000,4.000,4.000,4.000,4.000,4.000,4.000,4.000,4.000,4.000
14,2014-12-31,4.500,4.500,4.500,4.500,4.500,4.500,4.750,4.750,4.750,4.750,4.750,4.750
15,2015-12-31,4.750,4.750,4.750,4.750,4.750,4.750,4.750,4.750,4.750,4.750,4.250,4.250
16,2016-12-31,4.250,4.250,4.250,4.250,4.250,4.250,4.250,4.250,4.250,4.250,4.250,4.250
17,2017-12-31,4.250,4.250,4.250,4.750,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.000
18,2018-12-31,5.000,5.000,5.750,5.750,5.750,6.750,6.750,6.750,6.750,6.750,6.750,6.750
19,2019-12-31,6.750,7.750,7.750,7.750,7.750,7.750,7.750,7.750,7.750,7.750,7.750,7.750
20,2020-12-31,7.750,7.750,6.750,6.750,6.750,6.750,6.750,6.750,6.750,6.250,6.250,6.250
21,2021-12-31,6.250,6.250,6.250,6.250,6.250,6.250,6.250,6.250,6.250,6.250,6.250,6.250
22,2022-12-31,6.250,6.250,6.250,6.250,7.000,7.000,7.000,7.000,7.000,7.250,7.250,7.250
23,2023-12-31,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000
24,2024-12-31,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000,8.000
25,2025-12-31,8.000,8.000,7.500,7.500,7.500,7.500,7.500,7.500,7.500,7.500,7.500,7.500

In [24]:
import pandas as pd

# Lire le fichier
taux_interet_df = pd.read_excel('/content/datasets2/taux_interet.xlsx')

# Supprimer les espaces autour des noms de colonnes
taux_interet_df.columns = taux_interet_df.columns.str.strip()

# Renommer la colonne année pour plus de clarté
taux_interet_df.rename(columns={'Date/Indicateurs':'year'}, inplace=True)

# Filtrer juste de 2015 à 2025 (inclus)
taux_interet_df = taux_interet_df[(taux_interet_df['year'].dt.year >= 2015) &
                                  (taux_interet_df['year'].dt.year <= 2025)]

taux_interet_df.head()

,year,Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre
15,2015-12-31,4.75,4.75,4.75,4.75,4.75,4.75,4.75,4.75,4.75,4.75,4.25,4.25
16,2016-12-31,4.25,4.25,4.25,4.25,4.25,4.25,4.25,4.25,4.25,4.25,4.25,4.25
17,2017-12-31,4.25,4.25,4.25,4.75,5.00,5.00,5.00,5.00,5.00,5.00,5.00,5.00
18,2018-12-31,5.00,5.00,5.75,5.75,5.75,6.75,6.75,6.75,6.75,6.75,6.75,6.75
19,2019-12-31,6.75,7.75,7.75,7.75,7.75,7.75,7.75,7.75,7.75,7.75,7.75,7.75

In [25]:
# Transformer “large → long”
df_long = taux_interet_df.melt(
    id_vars=['year'],
    value_vars=['Janvier','Février','Mars','Avril','Mai','Juin',
                'Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    var_name='month',
    value_name='taux_interet'
)

In [26]:
# Dictionnaire mois français → numéro
mois_dict = {
    'Janvier':1, 'Février':2, 'Mars':3, 'Avril':4, 'Mai':5, 'Juin':6,
    'Juillet':7, 'Août':8, 'Septembre':9, 'Octobre':10, 'Novembre':11, 'Décembre':12
}

df_long['month_num'] = df_long['month'].map(mois_dict)

# Créer une date au premier jour du mois
df_long['date'] = pd.to_datetime(dict(
    year=df_long['year'].dt.year,
    month=df_long['month_num'],
    day=1
))

# Garder uniquement les colonnes utiles
df_long = df_long[['date','taux_interet']].sort_values('date').reset_index(drop=True)
df_long.head()

        date  taux_interet
0 2015-01-01          4.75
1 2015-02-01          4.75
2 2015-03-01          4.75
3 2015-04-01          4.75
4 2015-05-01          4.75

In [27]:
df_long

          date  taux_interet
0   2015-01-01          4.75
1   2015-02-01          4.75
2   2015-03-01          4.75
3   2015-04-01          4.75
4   2015-05-01          4.75
..         ...           ...
127 2025-08-01          7.50
128 2025-09-01          7.50
129 2025-10-01          7.50
130 2025-11-01          7.50
131 2025-12-01          7.50

[132 rows x 2 columns]

In [28]:
# Mettre date en index pour resample
df_daily = df_long.set_index('date').resample('D').ffill().reset_index()
df_daily.head(10)

        date  taux_interet
0 2015-01-01          4.75
1 2015-01-02          4.75
2 2015-01-03          4.75
3 2015-01-04          4.75
4 2015-01-05          4.75
5 2015-01-06          4.75
6 2015-01-07          4.75
7 2015-01-08          4.75
8 2015-01-09          4.75
9 2015-01-10          4.75

In [29]:
df_daily

           date  taux_interet
0    2015-01-01          4.75
1    2015-01-02          4.75
2    2015-01-03          4.75
3    2015-01-04          4.75
4    2015-01-05          4.75
...         ...           ...
3983 2025-11-27          7.50
3984 2025-11-28          7.50
3985 2025-11-29          7.50
3986 2025-11-30          7.50
3987 2025-12-01          7.50

[3988 rows x 2 columns]

In [30]:
# Filtrer exactement entre 2015-01-01 et 2026-01-01
df_daily = df_daily[(df_daily['date'] >= '2015-01-01') & (df_daily['date'] <= '2026-01-01')]
df_daily.head()
df_daily.tail()

           date  taux_interet
3983 2025-11-27           7.5
3984 2025-11-28           7.5
3985 2025-11-29           7.5
3986 2025-11-30           7.5
3987 2025-12-01           7.5

In [32]:
df_daily.to_excel('taux_interet_daily.xlsx', index=False)